### ISSUE TITLE
More convenient OS pasting

### ISSUE THREAD

**Issue by jonathanasquier** [sd65/MiniVim#13]
Hi,

I'm having a strange behaviour when pasting lines with multiple leading tabs :

```
[_]stuff 1
[_]stuff 2
[_]stuff 3

# paste it :

[_]stuff 1
[_]stuff 2
[_]stuff 3
```

but

```
[_][_]stuff 1
[_][_]stuff 2
[_][_]stuff 3

# paste it :

[_][_]stuff 1
[_][_][_][_]stuff 2
[_][_][_][_][_][_]stuff 3
```

How could I prevent that?
Awesome job by the way, I put it on every laptop/VM...

**Comment by sd65** [comment]
Hi,

This is a known behavior. Vim behave differently if you are copying from Windows, Linux, Putty, etc.

My advice is to use internal Vim clipboard. It works well. You can copy and paste easily with keys. 
Now, if you to copy from your OS to Vim, you can try to toggle "setpaste" (F2 with Minivim). Set it on and paste in Insert mode, set if off right after to not mess with key bindings.

I know this is not a perfect solution but it's not related to Minivim. However, I'll try to make it more easy in a future release.

**Comment by sd65** [comment]
Hi,
I investigate a bit more and there is not no magic solution for easy pasting in Vim.

First, because pasting in a terminal is different from pasting from gVim. 
Secondly, paste has to be messed up with indent when you activate autoindent. And autoindent is too great to miss.

So, use F2 to toggle setpaste and paste when off. This is the better answer.
Or use gVim !
