### ISSUE TITLE
Include a package manager

### ISSUE THREAD

**Issue by Thiht** [sd65/MiniVim#6]
I'm thinking [Vundle](https://github.com/VundleVim/Vundle.vim) maybe?

If so it would also be nice to install a few plugins by default: [NertTree](https://github.com/scrooloose/nerdtree) at the very least is a must-have!

**Comment by sd65** [comment]
Using a package manager is great, I like it too. But it's not portable, it has dependencies and multiple files. You could say that you can check if the plugin exists and download it if not. That's true and not so bad. But I use MiniVim with computers with no easy access to the internet. So that's not option. Anyway, the process is a bit heavy.

NerdTree is a very good plugin that I like, even the fact that the integrated file browser (Netrw) is pretty fine. But the argument is the same, MiniVim is minimalist and run with one file only. I encourage you to create a custom config [as described here](https://github.com/sd65/MiniVim/issues/4) to install your package manager and all your stuffs.

Let me know if you disagree. :-)
